apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  annotations:
    kubernetes.io/change-cause: "changes v3"
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 4
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-v3
        image: nginx

# to check rollout history and undo the prev changes use below cmds
# kubectl rollout history deploy
# kubectl rollout undo deploy