apiVersion: v1
kind: Pod
metadata:
  name: pod-port
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    -  name: web-port
       containerPort: 80
       protocol: TCP

# command for port forwarding
# kubectl port-forward pod-port 8080:80