apiVersion: "v1"
kind: Pod
metadata:
  name: pod-task
spec:
  restartPolicy: OnFailure
  containers:
  - name: pod-task
    image: vinsdocker/k8s-pod-assignment
    env:
    - name: NUMBER
      value: "5"
    args: 
    - "MY_ARG"